# Generated by Django 5.1.5 on 2025-02-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0001_initial'),
        ('user', '0004_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='olx.category'),
            preserve_default=False,
        ),
    ]
