# Generated by Django 5.1.5 on 2025-02-27 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_delete_ads'),
        ('user', '0005_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='carousel1',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='carousel2',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='carousel3',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olx.category'),
        ),
    ]
