# Generated by Django 5.1.5 on 2025-02-28 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_interested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested',
            name='user',
        ),
        migrations.AddField(
            model_name='interested',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.posts'),
        ),
        migrations.AddField(
            model_name='interested',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interested',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interested',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
