# Generated by Django 5.1.5 on 2025-02-19 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('carousel1', models.ImageField(null=True, upload_to='ads/')),
                ('carousel2', models.ImageField(null=True, upload_to='ads/')),
                ('carousel3', models.ImageField(null=True, upload_to='ads/')),
                ('carousel4', models.ImageField(null=True, upload_to='ads/')),
                ('carousel5', models.ImageField(null=True, upload_to='ads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.category')),
            ],
        ),
    ]
