# Generated by Django 5.1.5 on 2025-02-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
